### ISSUE TITLE
addtag [outofboundindex] t/ will reflect wrong result display as compared to edit [outofboundindex] t/

### ISSUE THREAD

**Issue by conantteo** [CS2103AUG2017-W11-B3/main#61]
![image](https://user-images.githubusercontent.com/28505402/32363654-5a87c2c4-c0ab-11e7-91a4-7309ff5a0bba.png)

**Comment by k-l-a** [comment]
I think this is caused by having the prefix be parsed by the command as the intended tag. 
(i.e. the program is thinking you want to add the tag `t/new` which contains the character `/` that violates the alphanumeric requirement)

Instead the command for adding a `new` tag to the entry with index 7 in the current list (which I think is the intention), should be `addtag 7 new`.

This is not a bug per se, as the format for addtag and deletetag does not specify that you should use `t/` prefix. It might be nice if the command can anticipate and parse this accordingly, though.
